### ISSUE TITLE
Algorithms to add

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/EC-Bestiary#2]
Mine blast algorithm for optimization of truss structures with discrete variable

**Comment by fcampelo** [comment]
Done.

**Comment by fcampelo** [comment]
More:
Biogeography-based optimisation
Small-world optimization algorithm for function optimisation
Curved Space Optimization: A Random Search based on GeneralRelativity Theory
Termite: A swarm intelligent routing algorithm for mobile wireless ad-hoc networks
Wasp swarm algorithm for dynamic MAX-SAT problems
A novel global convergence algorithm: bee collecting pollen algorithm
Optimization based on bacterial chemotaxis
A new fruit fly optimization algorithm: taking the financial distress model as an example
A Dolphin Partner Optimization

**Comment by caranha** [comment]
Added some of the papers above on commit 368e358

* Biogeography -- Added
* Small World -- Added
* ~~Curved Space~~ -- Not published (arxiv preprint only), what do?
* Termite -- Added Phd dissertation, couldn't find the DOI
* Wasp -- Added 2005 book chapter, couldn't find the DOI
* ~~Bee collecting~~ -- We already have bees?
* Bacterial Chemostasis -- Added
* Fruit Fly -- Added
* Dolphins -- Replaced existing paper because this one has an earlier date
